# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 
   
      - name: Fetch all history for all tags and branches
        run: |
          git fetch --prune
          git fetch --tags
          git branch --create-reflog master origin/master
            
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.4
        with:
          versionSpec: '5.3.x'
          
      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9.4

      - name: Display Version (debug)
        run: echo "Trying to use version ${{ steps.gitversion.outputs.nuGetVersionV2 }}"

      - name: Find and Replace Version
        run: find *.nuspec -type f -exec sed -i ''s/#{VERSION}#/${{ steps.gitversion.outputs.nuGetVersionV2 }}/g'' {} \;

      - name: Choco Pack
        uses: crazy-max/ghaction-chocolatey@v1.4.0
        with:
          args: pack
      
      - name: Choco Login
        uses: crazy-max/ghaction-chocolatey@v1.4.0
        if: github.ref == 'refs/heads/master'
        with:
          args: apikey --key ${{ secrets.CHOCO_API_KEY }} --source https://push.chocolatey.org/

      - name: Choco Push
        uses: crazy-max/ghaction-chocolatey@v1.4.0
        if: github.ref == 'refs/heads/master'
        with:
          args: push abaclient.${{ steps.gitversion.outputs.nuGetVersionV2 }}.nupkg --source https://push.chocolatey.org/ 


